dev: rename npm script `test:unit` to `test`
This is so that you can run tests with `npm test` instead of `npm run XXX`.

This also deletes the `test:e2e` command, which isn't currently working on my machine anyways, failing with this error:

```
Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ value:
   { message:
      "session not created: Chrome version must be between 71 and 75\n
      (Driver info: chromedriver=2.46.628411
      (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e)latform=Mac OS X 10.13.6
      x86_64) (WARNING: The server did not provide any stacktrace
      information)\nCommand duration or timeout: 1.85 seconds\nBuild
      info: version: '3.141.59', revision: 'e82be7d358', time:
      '2018-11-14T08:25:53'\nSystem info: host: 'waleedkhan.local', ip:
      'fe80:0:0:0:1c66:8be8:c376:a374%en0', os.name: 'Mac OS X',
      os.arch: 'x86_64', os.version: '10.13.6', java.version:
      '1.8.0_74'\nDriver info: driver.version: unknown",
           error: 'session not created' },
             status: 33 }
```